// Generated by scripts/generate-color-usage.mjs — do not edit
// Re-run: npm run colors:usage
export type ColorSwatch = {
  name: string;
  class?: string;
  style?: string;
  hex?: string;
};

export type ColorSection = {
  title: string;
  colors: ColorSwatch[];
};

export const colorSections: ColorSection[] = [
  {
    title: 'Brand',
    colors: [
      { name: 'black', class: 'bg-black', hex: '#2E2D2C' },
      { name: 'current', class: 'bg-current' },
      { name: 'transparent', class: 'bg-transparent' },
      { name: 'white', class: 'bg-white', hex: '#FFFFFF' },
    ],
  },
  {
    title: 'Accent',
    colors: [
      { name: 'accent', class: 'bg-accent', hex: '#39CCFB' },
    ],
  },
  {
    title: 'Studio',
    colors: [
      { name: 'studio-dark', class: 'bg-studio-dark', hex: '#64748B' },
      { name: 'studio-forest', class: 'bg-studio-forest', hex: '#102F35' },
      { name: 'studio-green', class: 'bg-studio-green', hex: '#B9E86C' },
      { name: 'studio-lime', class: 'bg-studio-lime', hex: '#D7FE96' },
      { name: 'studio-yellow', class: 'bg-studio-yellow', hex: '#FBFF96' },
    ],
  },
  {
    title: 'Error',
    colors: [
      { name: 'error', class: 'bg-error', hex: '#DC2626' },
      { name: 'error-light', class: 'bg-error-light', hex: '#FECACA' },
    ],
  },
  {
    title: 'CSS Variables',
    colors: [
      { name: '--primary-color', style: 'background: var(--primary-color)', hex: '#39CCFB' },
      { name: '--secondary-color', style: 'background: var(--secondary-color)', hex: '#34D399' },
    ],
  },
  {
    title: 'Gray',
    colors: [
      { name: 'gray-100', class: 'bg-gray-100' },
      { name: 'gray-200', class: 'bg-gray-200' },
      { name: 'gray-300', class: 'bg-gray-300' },
      { name: 'gray-400', class: 'bg-gray-400' },
      { name: 'gray-50', class: 'bg-gray-50' },
      { name: 'gray-500', class: 'bg-gray-500' },
      { name: 'gray-600', class: 'bg-gray-600' },
      { name: 'gray-700', class: 'bg-gray-700' },
      { name: 'gray-800', class: 'bg-gray-800' },
      { name: 'gray-900', class: 'bg-gray-900' },
    ],
  },
  {
    title: 'Blue',
    colors: [
      { name: 'blue-100', class: 'bg-blue-100' },
      { name: 'blue-200', class: 'bg-blue-200' },
      { name: 'blue-400', class: 'bg-blue-400' },
      { name: 'blue-50', class: 'bg-blue-50' },
      { name: 'blue-500', class: 'bg-blue-500' },
      { name: 'blue-600', class: 'bg-blue-600' },
      { name: 'blue-700', class: 'bg-blue-700' },
      { name: 'blue-800', class: 'bg-blue-800' },
      { name: 'blue-900', class: 'bg-blue-900' },
    ],
  },
  {
    title: 'Green',
    colors: [
      { name: 'green-100', class: 'bg-green-100' },
      { name: 'green-200', class: 'bg-green-200' },
      { name: 'green-400', class: 'bg-green-400' },
      { name: 'green-500', class: 'bg-green-500' },
      { name: 'green-600', class: 'bg-green-600' },
      { name: 'green-700', class: 'bg-green-700' },
      { name: 'green-800', class: 'bg-green-800' },
    ],
  },
  {
    title: 'Red',
    colors: [
      { name: 'red-100', class: 'bg-red-100' },
      { name: 'red-300', class: 'bg-red-300' },
      { name: 'red-400', class: 'bg-red-400' },
      { name: 'red-50', class: 'bg-red-50' },
      { name: 'red-500', class: 'bg-red-500' },
      { name: 'red-600', class: 'bg-red-600' },
      { name: 'red-800', class: 'bg-red-800' },
    ],
  },
  {
    title: 'Yellow',
    colors: [
      { name: 'yellow-100', class: 'bg-yellow-100' },
      { name: 'yellow-50', class: 'bg-yellow-50' },
      { name: 'yellow-500', class: 'bg-yellow-500' },
      { name: 'yellow-600', class: 'bg-yellow-600' },
      { name: 'yellow-800', class: 'bg-yellow-800' },
    ],
  },
  {
    title: 'Indigo',
    colors: [
      { name: 'indigo-200', class: 'bg-indigo-200' },
      { name: 'indigo-50', class: 'bg-indigo-50' },
      { name: 'indigo-500', class: 'bg-indigo-500' },
      { name: 'indigo-600', class: 'bg-indigo-600' },
      { name: 'indigo-700', class: 'bg-indigo-700' },
    ],
  },
  {
    title: 'Amber',
    colors: [
      { name: 'amber-100', class: 'bg-amber-100' },
      { name: 'amber-700', class: 'bg-amber-700' },
    ],
  },
  {
    title: 'Emerald',
    colors: [
      { name: 'emerald-500', class: 'bg-emerald-500' },
    ],
  },
  {
    title: 'Orange',
    colors: [
      { name: 'orange-100', class: 'bg-orange-100' },
      { name: 'orange-700', class: 'bg-orange-700' },
    ],
  },
  {
    title: 'Violet',
    colors: [
      { name: 'violet-100', class: 'bg-violet-100' },
      { name: 'violet-50', class: 'bg-violet-50' },
      { name: 'violet-600', class: 'bg-violet-600' },
      { name: 'violet-700', class: 'bg-violet-700' },
    ],
  },
];
