/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class ActivitySchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'locale', 'userId'] as const;
  $columns = ActivitySchema.$columns;
  @column()
  declare action: string;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare locale: string;
  @column()
  declare userId: number | null;
}

export class CampaignSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'bundle',
    'createdAt',
    'id',
    'isPublished',
    'locale',
    'stats',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = CampaignSchema.$columns;
  @column()
  declare apiVersion: number;
  @column()
  declare bundle: any;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare isPublished: boolean;
  @column()
  declare locale: string;
  @column()
  declare stats: any;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class ChapterSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'bundle',
    'createdAt',
    'id',
    'locale',
    'number',
    'storyId',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = ChapterSchema.$columns;
  @column()
  declare apiVersion: number;
  @column()
  declare bundle: any;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare locale: string;
  @column()
  declare number: number;
  @column()
  declare storyId: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class DraftSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'bundle',
    'createdAt',
    'feedback',
    'id',
    'locale',
    'number',
    'status',
    'storyId',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = DraftSchema.$columns;
  @column()
  declare apiVersion: number;
  @column()
  declare bundle: any;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare feedback: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare locale: string;
  @column()
  declare number: number;
  @column()
  declare status: any;
  @column()
  declare storyId: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class DropSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'bundle',
    'coverImage',
    'createdAt',
    'id',
    'isPublished',
    'releaseAt',
    'streamId',
    'title',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = DropSchema.$columns;
  @column()
  declare apiVersion: number;
  @column()
  declare bundle: any;
  @column()
  declare coverImage: string | null;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare isPublished: boolean;
  @column.dateTime()
  declare releaseAt: DateTime | null;
  @column()
  declare streamId: number;
  @column()
  declare title: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class IndexSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'createdAt',
    'draftsList',
    'id',
    'issuesList',
    'items',
    'locale',
    'publishedList',
    'storyId',
    'updatedAt',
  ] as const;
  $columns = IndexSchema.$columns;
  @column()
  declare apiVersion: number;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare draftsList: any;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare issuesList: any;
  @column()
  declare items: any;
  @column()
  declare locale: string;
  @column()
  declare publishedList: any;
  @column()
  declare storyId: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}

export class PageSchema extends BaseModel {
  static $columns = [
    'apiVersion',
    'bundle',
    'createdAt',
    'id',
    'isPublished',
    'locale',
    'order',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = PageSchema.$columns;
  @column()
  declare apiVersion: number;
  @column()
  declare bundle: any;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare isPublished: boolean;
  @column()
  declare locale: string;
  @column()
  declare order: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class PreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'settings', 'updatedAt', 'userId'] as const;
  $columns = PreferenceSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare settings: any;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare userId: number | null;
}

export class UiAttributeSchema extends BaseModel {
  static $columns = ['description', 'id', 'key', 'placeholders'] as const;
  $columns = UiAttributeSchema.$columns;
  @column()
  declare description: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare key: string;
  @column()
  declare placeholders: any | null;
}

export class UiSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'flag',
    'id',
    'key',
    'locale',
    'microCopy',
    'updatedAt',
    'updatedBy',
  ] as const;
  $columns = UiSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare flag: any | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare key: string;
  @column()
  declare locale: string;
  @column()
  declare microCopy: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare updatedBy: number | null;
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'id',
    'language',
    'name',
    'password',
    'rememberMeToken',
    'resetToken',
    'resetTokenCreatedAt',
    'role',
    'updatedAt',
  ] as const;
  $columns = UserSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare email: string;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare language: string | null;
  @column()
  declare name: string;
  @column({ serializeAs: null })
  declare password: string;
  @column()
  declare rememberMeToken: string | null;
  @column()
  declare resetToken: string | null;
  @column.dateTime()
  declare resetTokenCreatedAt: DateTime | null;
  @column()
  declare role: any;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}
